# Generated by Django 5.1.1 on 2024-10-21 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{14}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$')])),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('patient', 'Prescription')], max_length=20)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('clinic', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('pharmacy_name', models.CharField(blank=True, max_length=255)),
                ('pharmacy_address', models.CharField(blank=True, max_length=255)),
                ('diabetes', models.BooleanField(blank=True, default=False)),
                ('heart_disease', models.BooleanField(blank=True, default=False)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('other_diseases', models.TextField(blank=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
